# Generated by Django 5.1 on 2025-08-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_appointment_book_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='customer',
            new_name='user_id',
        ),
    ]
