# Generated by Django 5.1 on 2025-08-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_customer_appointment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='business',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
