# Generated by Django 5.1 on 2025-08-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_question_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
    ]
