# Generated by Django 5.1 on 2025-08-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, choices=[('mother_maiden', "What is your mother's maiden name?"), ('first_pet', 'What was the name of your first pet?'), ('favorite_color', 'What is your favorite color?')], max_length=50, null=True, unique=True),
        ),
    ]
