# Generated by Django 5.1 on 2025-08-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='question',
            new_name='recovery_question',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(choices=[('mother_maiden', "What is your mother's maiden name?"), ('first_pet', 'What was the name of your first pet?'), ('favorite_color', 'What is your favorite color?')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
