# Generated by Django 5.1 on 2025-08-28 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_answer_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='recovery_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.question'),
        ),
    ]
