# Generated by Django 5.1 on 2025-08-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_answer_recovery_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='msg_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
